// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClZa7ku54KKGL_JOhwl-9tcZ8QWzI_oAs',
    appId: '1:130710060687:web:045a469f5428e8075c3afa',
    messagingSenderId: '130710060687',
    projectId: 'parkaholic2',
    authDomain: 'parkaholic2.firebaseapp.com',
    storageBucket: 'parkaholic2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBd8Oh2sbZQODIz5i74RWhoTEa9_jbtno',
    appId: '1:130710060687:android:687e081fad5981515c3afa',
    messagingSenderId: '130710060687',
    projectId: 'parkaholic2',
    storageBucket: 'parkaholic2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrDohhj9buz1a-KJZ2tH5hW7GRgzPJkDc',
    appId: '1:130710060687:ios:92ea701ece9a71b65c3afa',
    messagingSenderId: '130710060687',
    projectId: 'parkaholic2',
    storageBucket: 'parkaholic2.appspot.com',
    iosClientId: '130710060687-8ilke0q81dib50atemursdm1slqtn1ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrDohhj9buz1a-KJZ2tH5hW7GRgzPJkDc',
    appId: '1:130710060687:ios:92ea701ece9a71b65c3afa',
    messagingSenderId: '130710060687',
    projectId: 'parkaholic2',
    storageBucket: 'parkaholic2.appspot.com',
    iosClientId: '130710060687-8ilke0q81dib50atemursdm1slqtn1ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.src',
  );
}
