// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIiUYWgwleXHnPffAAz6YV2Fq_7-zC7RY',
    appId: '1:419364246861:web:1c6c470408d476683e5304',
    messagingSenderId: '419364246861',
    projectId: 'parkaholic-d1d2f',
    authDomain: 'parkaholic-d1d2f.firebaseapp.com',
    storageBucket: 'parkaholic-d1d2f.appspot.com',
    measurementId: 'G-LVR0P1DPB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB34OUnKxwa6LgxEqj5s5cH1xobE0TscGU',
    appId: '1:419364246861:android:5e0ec6837800afd43e5304',
    messagingSenderId: '419364246861',
    projectId: 'parkaholic-d1d2f',
    storageBucket: 'parkaholic-d1d2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCB_IGwH1KqiEuYL6mTCAsE2BlujcKCqE',
    appId: '1:419364246861:ios:5a8c5b19513262f73e5304',
    messagingSenderId: '419364246861',
    projectId: 'parkaholic-d1d2f',
    storageBucket: 'parkaholic-d1d2f.appspot.com',
    iosClientId:
        '419364246861-7jsrg40qgarhku2hlt0bp6mm6mq9r212.apps.googleusercontent.com',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCB_IGwH1KqiEuYL6mTCAsE2BlujcKCqE',
    appId: '1:419364246861:ios:5a8c5b19513262f73e5304',
    messagingSenderId: '419364246861',
    projectId: 'parkaholic-d1d2f',
    storageBucket: 'parkaholic-d1d2f.appspot.com',
    iosClientId:
        '419364246861-7jsrg40qgarhku2hlt0bp6mm6mq9r212.apps.googleusercontent.com',
    iosBundleId: 'com.example.src',
  );
}
